/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kissmedia_android_VideoTrimmer */

#ifndef _Included_kissmediatest_android_VideoTrimmer
#define _Included_kissmediatest_android_VideoTrimmer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kissmedia_android_VideoTrimmer
 * Method:    trim
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_kissmediatest_android_VideoTrimmer_trim
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
